---
- name: Add the petclinic user
  ansible.builtin.user:
    name: petclinic
    shell: /usr/bin/false
    system: yes

- name: Crete petclinic directory and change ownership
  ansible.builtin.file:
    path: /opt/petclinic
    state: directory
    recurse: yes
    owner: petclinic
    group: petclinic

- name: Copy petclinic.service file
  ansible.builtin.template:
      src: petclinic.service.j2
      dest: /etc/systemd/system/petclinic.service 
  notify: Daemon_reload

- name: Enable and start petclinic
  ansible.builtin.service:
    name: petclinic
    state: restarted
    enabled: yes